### ISSUE TITLE
Allow local non-root certificate generation

### ISSUE THREAD

**Issue by vinjana** [openmicroscopy/ansible-role-ssl-certificate#15]
## Use Case

Create SSL certificates locally. In a second step (another role) the certificates could then be distributed to the remote hosts.

## Current situation

Non-root user without sudo rights cannot create certificates with the role locally. E.g. running

```yaml
- name: Local preparations
  hosts: localhost
  roles:
    - role: ome.ssl_certificate
```

fails, because the role requires sudo rights.

## Improvement

Remove the `become: true` from the tasks in `tasks/main.yml`. This allows normal users to generate certificates locally. E.g.

```yaml
- name: Local preparations
  hosts: localhost
  roles:
    - role: ome.ssl_certificate
  vars:
    ssl_certificate_selfsigned_create: True
    ssl_certificate_selfsigned_subject: "/CN=localhost"
    ssl_certificate_selfsigned_days: 365
    ssl_certificate_public_path: etc/ssl/localcerts/global.crt.pem
    ssl_certificate_key_path: etc/ssl/localcerts/global.key.pem
    ssl_certificate_bundled_path: etc/ssl/localcerts/global.bundled.crt
    ssl_certificate_combined_path: etc/ssl/localcerts/global.combined.pem
```

The old use-case, remote certificates with root rights can easily be reproduced with

```yaml
- name: Local preparations
  hosts: localhost
  become: true
  roles:
    - role: ome.ssl_certificate
```
